### ISSUE TITLE
Add other method for removing outliers.

### ISSUE THREAD

**Issue by c-bata** [c-data/outlier-utils#5]
refs https://en.wikipedia.org/wiki/Outlier

**Comment by chucklesoclock** [comment]
But there's so many T-T

**Comment by c-bata** [comment]
`pandas` may be going to implement the function for dropping outliers.
But `pandas` has no dependency on `scipy` . So it's a little difficult to implement the method required t-value(scipy.stats.t) like Smirnov grubbs tests or Thompsonぴ Tau test.
So I think this library should implements these methods.

refs: https://github.com/pandas-dev/pandas/issues/15111
